services:
  front-end:
    container_name: front-end
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped

  back-end:
    container_name: back-end
    build:
      context: ./back-end
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_started
    restart: unless-stopped

  database:
    container_name: database
    image: postgres:alpine
    volumes:
      - ./database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    restart: unless-stopped
